# https://decapcms.org/docs/backends-overview/
backend:
  name: git-gateway # adds users without giving them direct write access to your GitHub or GitLab repository.
  branch: main # default: master
  cms_label_prefix: decap-cms # default: netlify-cms/
  # Options:
  # name: github/gitlab/bitbucket # all users added must have push access to your content repository.
  # repo: owner-name/repo-name # Path to your GitHub repository

# https://decapcms.org/docs/configuration-options/
publish_mode: editorial_workflow
display_url: https://vuedn.netlify.app/
media_folder: "src/assets" # Media files will be stored in the repo under docs/.vuepress/public/media
public_folder: " /assets" # The src attribute for uploaded media will begin with /media
i18n:
  structure: "multiple_folders"
  locales: ["zh","en", "ja"]
  default_locale: "zh"
editor:
  preview: false # disabled markdown preview in CMS
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/songs
    label: "Blog Posts" # Used in the UI
    i18n: true
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    slug: "{{customSlug}}" # Filename template # Outputs sun-apr-02-2023-01-13-17-gmt-0300-east-africa-time (not ideal but is dynamic to date - only at creation not at editing)
    fields: # The fields for each document, usually in front matter
      - {label: "Post Title", name: "title", widget: "string", i18n: true}
      - {label: "FileName", name: "customSlug", widget: "string", i18n: "duplicate"}
      - {label: "Draft", name: "draft", widget: "boolean", i18n: "duplicate"}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}
      - label: Image
        name: image
        widget: object
        i18n: true
        fields:
          - label: Source
            name: src
            widget: image
            i18n: duplicate
          - label: Alt Text
            name: alt
            widget: string
            i18n: true
      - {label: "Snippet", name: "snippet", widget: "text", i18n: true}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD HH:mm", i18n: "duplicate"}
      - {label: "Category", name: "category", widget: "select", options: ["Development", "Business", "Design", "Life"], i18n: "duplicate"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
